version: '3.9'

services:
  michalskiba_dev_db:
    image: postgres:15.1
    container_name: michalskiba_dev_db
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - devel.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
  michalskiba_dev_web:
    image: michalskiba_dev_web
    container_name: michalskiba_dev_web
    volumes:
      - ./michalskiba_dev:/code
    env_file:
      - devel.env
    ports:
      - '8000:8000'
    command: bash -c 'python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      michalskiba_dev_db:
        condition: service_healthy
