version: '3.9'

services:
  michalskiba_dev_db:
    image: postgres:15.1
    container_name: michalskiba_dev_db
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - devel.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
  michalskiba_dev_wpt_db:
    image: postgres:15.1
    container_name: michalskiba_dev_wpt_db
    volumes:
      - ./wpt_data:/var/lib/postgresql/data
    env_file:
      - devel.env
    environment:
      - POSTGRES_DB=${POSTGRES_WPT_DB}
      - POSTGRES_USER=${POSTGRES_WPT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_WPT_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_WPT_PORT}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_WPT_DB} -U ${POSTGRES_WPT_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
  michalskiba_dev_web:
    image: michalskiba_dev_web
    container_name: michalskiba_dev_web
    volumes:
      - ./michalskiba_dev:/code
    env_file:
      - devel.env
    ports:
      - '8000:8000'
    command: bash -c 'python manage.py migrate &&
                      python manage.py migrate --database=web_parameter_tampering &&
                      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      michalskiba_dev_db:
        condition: service_healthy
      michalskiba_dev_wpt_db:
        condition: service_healthy
