version: "3.8"

services:
  frontend:
      container_name: michalskiba_dev_frontend
      image: klakegg/hugo:0.101.0-ext-alpine
      command: server -D
      volumes:
        - ./modules/frontend/src:/src
      ports:
        - "1313:1313"
      env_file:
        - ./modules/frontend/.env.dev

  proxy:
    image: nginx:alpine
    container_name: michalskiba_dev_proxy
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
