version=0.1

[default.local_start_api.parameters]
warm_containers="EAGER"
port=3001
parameter_overrides=[
  "Environment=Local",
  "AuthSecretKey=local-secret-key",
  "HostHeaderInjectionSecretKey=local-secret-key",
]

[default.validate.parameters]
profile="${PROFILE}"
lint=true

[default.build.parameters]
use_container="true"

[default.deploy.parameters]
stack_name="${STACK_NAME}",
resolve_s3=true
region="${REGION}"
capabilities=[
  "CAPABILITY_IAM",
]
parameter_overrides=[
  "Environment=Production",
  "AuthSecretKey=${AUTH_SECRET_KEY}",
  "HostHeaderInjectionSecretKey=${HOST_HEADER_INJECTION_SECRET_KEY}",
]
