AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a Lambda function with API Gateway

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - Local
      - Production
  AuthSecretKey:
    Type: String
    NoEcho: true

Mappings:
  EnvVariables:
    Local:
      AllowOrigin: http://localhost:1313
      CookieTemplate: "access_token={}; HttpOnly; SameSite=Lax; Path=/demo"
    Production:
      AllowOrigin: https://www.michalskiba.dev
      CookieTemplate: "access_token={}; Secure; HttpOnly; SameSite=Lax; Path=/demo"

Resources:
  SqlInjection:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: ./modules/sql_injection/src
      Handler: sql_injection.lambda_function.lambda_handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /demo/sql-injection
      Environment:
        Variables:
          DB_PATH: sql_injection/data.db
          ALLOW_ORIGIN: !FindInMap
            - EnvVariables
            - !Ref Environment
            - AllowOrigin
  Auth:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: ./modules/auth/src
      Handler: auth.lambda_function.lambda_handler
      MemorySize: 512
      Events:
        LoginApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: POST
            Path: /demo/auth/login
        LogoutApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: POST
            Path: /demo/auth/logout
      Environment:
        Variables:
          DB_PATH: auth/data.db
          ALLOW_ORIGIN: !FindInMap
            - EnvVariables
            - !Ref Environment
            - AllowOrigin
          COOKIE_TEMPLATE: !FindInMap
            - EnvVariables
            - !Ref Environment
            - CookieTemplate
          SECRET_KEY: !Ref AuthSecretKey
  WebParameterTampering:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: ./modules/web_parameter_tampering/src
      Handler: web_parameter_tampering.lambda_function.lambda_handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /demo/web-parameter-tampering
            Auth:
              Authorizer: CustomAuthorizer
      Environment:
        Variables:
          DB_PATH: web_parameter_tampering/data.db
          ALLOW_ORIGIN: !FindInMap
            - EnvVariables
            - !Ref Environment
            - AllowOrigin
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        CertificateArn: arn:aws:acm:eu-central-1:628924145931:certificate/c8335665-cc74-46ee-b24f-b615ac09a6c3
        DomainName: api.michalskiba.dev
      Auth:
        Authorizers:
          CustomAuthorizer:
            AuthorizerPayloadFormatVersion: "2.0"
            EnableFunctionDefaultPermissions: true
            EnableSimpleResponses: true
            FunctionArn:
              Fn::GetAtt:
                - Auth
                - Arn
