services:
  api_test:
    image: michalskiba_dev_api_test
    container_name: michalskiba_dev_api_test
    volumes:
      - ./pyproject.toml:/code/pyproject.toml
      - ./.coveragerc:/code/.coveragerc
      - ./requirements.test.txt:/code/requirements.test.txt
      - ./modules/auth:/code/auth
      - ./modules/core:/code/core
      - ./modules/host_header_injection:/code/host_header_injection
      - ./modules/sql_injection:/code/sql_injection
      - ./modules/web_parameter_tampering:/code/web_parameter_tampering
