# Generated by Django 4.2.5 on 2023-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("address", models.CharField(max_length=64)),
                ("opening_hours", models.CharField(max_length=64)),
                ("access_code", models.CharField(max_length=16)),
            ],
        ),
    ]
