# Generated by Django 4.2.3 on 2023-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("hashed_password", models.CharField(max_length=128)),
            ],
        ),
    ]
