[tool.isort]
profile = "black"
py_version = 312
extend_skip_glob = ['/code/lib/*']

[tool.black]
line-length = 99
target-version = ['py312']
extend-exclude = '/code/lib'

[tool.ruff]
line-length = 99
target-version = 'py311'
exclude = ['/code/lib']

[tool.mypy]
python_version = '3.12'
exclude =  ['(^|/)lib/']
follow_imports = 'skip'
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = false
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
extra_checks = true
ignore_missing_imports = true
