AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for a Lambda function with API Gateway

Resources:
  SQLInjectionAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src/sql_injection
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          DB_PATH: "sql_injection.db"
          ALLOW_ORIGIN: "http://localhost:1313"
