# Generated by Django 4.2.1 on 2023-06-01 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web_parameter_tampering", "0001_create_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("organization", models.CharField(max_length=64)),
                ("note", models.CharField(max_length=1024)),
                ("accepted", models.BooleanField(default=False)),
                ("accreditation_code", models.CharField(default=uuid.uuid4, max_length=36)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="press_application",
                        to="web_parameter_tampering.user",
                    ),
                ),
            ],
        ),
    ]
