# Generated by Django 4.2.1 on 2023-06-01 15:05
from typing import Any

from django.db import migrations


def apply(apps: Any, schema_editor: Any) -> None:
    User = apps.get_model("web_parameter_tampering", "User")
    User.objects.bulk_create(
        [
            User(
                username="hacker",
                hashed_password="$2b$12$q7HlotRVicR37NYM6aY.UOiKMPlSjA8qLk4pWeijxbeZD.5Be919i",
            ),
            User(
                username="victim",
                hashed_password="$2b$12$V.k71jJvQkwENITl.3wts.nKwoVCKIpxda.JqEMQgg3YMQ.3IhNhO",
            ),
        ]
    )


def revert(apps: Any, schema_editor: Any) -> None:
    User = apps.get_model("web_parameter_tampering", "User")
    User.objects.filter(username__in=["hacker", "victim"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web_parameter_tampering", "0002_create_press_application_model"),
    ]

    operations = [
        migrations.RunPython(apply, revert),
    ]
