# Generated by Django 4.2.1 on 2023-06-01 15:05
from typing import Any

import bcrypt
from django.db import migrations


def apply(apps: Any, schema_editor: Any) -> None:
    User = apps.get_model("web_parameter_tampering", "User")
    User.objects.bulk_create(
        [
            User(
                username="hacker",
                hashed_password=bcrypt.hashpw(
                    "Hacker1234!".encode("utf-8"), bcrypt.gensalt()
                ).decode("utf-8"),
            ),
            User(
                username="victim",
                hashed_password=bcrypt.hashpw(
                    "Victim1234!".encode("utf-8"), bcrypt.gensalt()
                ).decode("utf-8"),
            ),
        ]
    )


def revert(apps: Any, schema_editor: Any) -> None:
    User = apps.get_model("web_parameter_tampering", "User")
    User.objects.filter(username__in=["hacker", "victim"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web_parameter_tampering", "0002_create_press_application_model"),
    ]

    operations = [
        migrations.RunPython(apply, revert),
    ]
