# Generated by Django 4.2.1 on 2023-06-01 15:19
from typing import Any

from django.db import migrations


def apply(apps: Any, schema_editor: Any) -> None:
    PressApplication = apps.get_model("web_parameter_tampering", "PressApplication")
    PressApplication.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web_parameter_tampering", "0004_press_applications"),
    ]

    operations = [
        migrations.RunPython(apply, migrations.RunPython.noop),
    ]
