# Generated by Django 4.2.3 on 2023-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_parameter_tampering", "0007_populate_press_applications"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
