[tool.black]
line-length = 99
target-version = ['py311']
extend-exclude = 'migrations'

[tool.ruff]
line-length = 99
target-version = 'py311'
exclude = ['migrations']

[tool.mypy]
plugins = 'mypy_django_plugin.main'
python_version = '3.11'
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = false
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = 'michalskiba_dev.settings'
ignore_missing_model_attributes = true

[tool.isort]
profile = "black"
py_version = 311
extend_skip_glob = ['*/migrations/*.py']
