version: "3.8"

services:
  frontend:
      container_name: michalskiba_dev_frontend
      image: klakegg/hugo:0.101.0-ext-alpine
      command: server -D
      volumes:
        - ./src:/src
      ports:
        - "1313:1313"
      env_file:
        - .env.dev
