# Generated by Django 4.1.5 on 2023-03-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('lead', models.TextField(max_length=512)),
                ('content_path', models.CharField(max_length=64, unique=True)),
                ('blog_post_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='blog.blogpostraw')),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='blog.tag')),
            ],
        ),
    ]
