# Generated by Django 4.2.1 on 2023-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_create_blog_post_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content_path",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpostraw",
            name="content_path",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
