[tool.isort]
profile = "black"
py_version = 312
extend_skip_glob = ['src/web_parameter_tampering/lib/*']

[tool.black]
line-length = 99
target-version = ['py312']
extend-exclude = 'src/web_parameter_tampering/lib'

[tool.ruff]
line-length = 99
target-version = 'py312'
exclude = ['src/web_parameter_tampering/lib']

[tool.mypy]
python_version = '3.12'
exclude =  ['(^|/)web_parameter_tampering/lib/']
follow_imports = 'normal'
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
extra_checks = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = '--cov-config=.coveragerc --cov-report= --cov=./'
filterwarnings = 'ignore::DeprecationWarning'
